//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEducation
    {
        public int ID { get; set; }
        public string Institution { get; set; }
        public string Faculty { get; set; }
        public string Department { get; set; }
        public string GPA { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime GraduationDate { get; set; }
    }
}
